spring.application.name=youtube
spring.datasource.url=jdbc:mysql://localhost:3306/youtube_db
spring.datasource.username=root
spring.datasource.password=root123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=7ca5c89189b501793d2aed198523aacd7af48a9a85084cfc5d0706ca58fc5ef1
jwt.expiration=3600000
aws.s3.region = eu-north-1

aws.accessKey=${AWS_ACCESS_KEY}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.s3.bucket=ammar-youtube-clone-2026
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB
